url: "https://jinxinhu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jacob's studio" # the name of your site, e.g. ACME Corp.
description: "My ordinary but extrordinary life."
