menu:
- {name: 'People', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/jinxinhu'}
- {icon: 'twitter', link: 'https://twitter.com'}
- {icon: 'instagram', link: 'https://instagram.com'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/'}

contacts:
- {name: 'Jinxin Hu', title: 'Master 1 student', department: 'Institute of Physics', institution: 'École polytechnique fédérale de Lausanne (EPFL)', institution_address: 'EPFL SB - SPH', phone: '(+41) 000-0000', email: 'jinxin.hu@epfl.ch', image: 'assets/img/EPFL.JPG'}
