menu:
- {name: 'Cooperation', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'WU Jian', title: 'Professor', department: 'Physics & Astronomy', institution: 'Harbin Institute of Technology', institution_address: 'No.92 Westdazhi Street, Harbin, Heilongjiang Province, China', phone: ' (+86) (0)451-86402324', email: ' jian.wu@hit.edu.cn', office: 'Dongli Building 602', image: 'assets/img/jianwu.jpeg', url: 'http://homepage.hit.edu.cn/jianwu?lang=en'}
- {name: 'AIGOUY Lionel', title: 'Chargé de Recherche CNRS', department: 'Physics', institution: 'ESPCI Paris - PSL', institution_address: '10 Rue Vauquelin, 75005 Paris', phone: '(+33) (0)1 40 79 45 36', email: 'lionel.aigouy@espci.fr', office: ' C132', image: 'assets/img/lionel.jpg', url: 'https://www.lpem.espci.fr/spip.php?article58&lang=fr'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/jinxinhu'}
- {icon: 'twitter', link: 'https://twitter.com'}
- {icon: 'instagram', link: 'https://instagram.com'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/'}

contacts:
- {name: 'Jinxin Hu', title: 'Master 1 student', department: 'Institute of Physics', institution: 'École polytechnique fédérale de Lausanne (EPFL)', institution_address: 'EPFL SB - SPH, Station Nº 3, CH - 1015 Lausanne', phone: '(+41) 000-0000', email: 'mailto:jinxin.hu@epfl.ch', office: 'PH A1 000', image: 'assets/img/EPFL.JPG'}
